### ISSUE TITLE
Beschreibung und Grundanforderungen ergänzen

### ISSUE THREAD

**Issue by madiko** [TobiasKrais/d2u_news#1]
Hallo Tobias,

lud mir soeben Dein AddOn herunter und stelle fest, dass ich es gar nicht verwenden kann. :-/ 

Daher meine Empfehlung: Gib in der Kurzbeschreibung zum AddOn noch folgende Infos an:

Es wird das AddOn d2u_helper benötigt!
Es wird das AddOn sprog benötigt!
Es wird das AddOn tinymce4 benötigt!
Es wird das AddOn url benötigt!
(Bitte weitere ergänzen, die hier nicht genannt sind, weil sie bei mir schon vorhanden waren.)

Bei der Gelegenheit: Es wäre gut, wenn z. B. nicht tinymce4 als Voraussetzung gesetzt wäre. Ich arbeite lieber mit Markitup und hätte gern die Wahl. Das geht vielleicht anderen auch so?

Viele Grüße,
Franziska

**Comment by TobiasKrais** [comment]
Hi Franziska,

ja, da hast du recht und schneidest du einen unschönen Punkt an. Allerdings möchte ich nicht für jedes meiner Addons die Abhängigkeiten an mehreren Orten überwachen müssen (config.yml und Beschreibung). Mir ist diese Lösung lieber: https://github.com/redaxo/redaxo/issues/469. Darauf warte ich und dulde bis zur Lösung diesen Mißstand. Andere Addons machen das auch so, siehe der Abhängigkeitsbaum von YRewrite.

Wegen der Abhängigkeit zu TinyMCE: auch da hast du Recht. Wir hatten das schon mal im Forum diskutiert, dass ich mir eine ODER Abhängigkeit in der config.yml wünsche. Das habe ich jetzt als Issue in Redaxo eingegeben: https://github.com/redaxo/redaxo/issues/1646. Ich selbst stand damals vor der Umstellung von Redactor auf TinyMCE und wollte gerne eigentlich beides ermöglichen.
Ich lassen den Bug mal offen. Wenn ich Zeit habe oder mich jemand bezahlt werde ich in meinem Helfer Addon eine Option einbauen was der Lieblingseditor ist und den Nutzer das aussuchen lassen.

Liebe Grüße,

Tobi

**Comment by skerbis** [comment]
Warum sich auf irgendwelche Editoren versteifen? In einer Setup-Seite könnte man das dem User per Attributzuweisung selbst überlassen.

**Comment by TobiasKrais** [comment]
Du deutest an, dass es eine Möglichkeit gibt, komplett flexibel zu sein. Wie würdest du das lösen?

**Comment by skerbis** [comment]
Ich kenne Dein AddOn nicht, aber... du könntest ein Feld in deiner Config zur Verfügung stellen in der du nach Attributen für die Textfelder fragst. Die Editoren achten ja auf die entsprechende CSS-Class oder bei CK auf ein zusätzliches Attribut. 

Ggf. könntest du diese auch für den ersten gefundenen was vorbelegen. Wodurch man sofort loslegen kann. 

Vorteil: Du musst dich auch um zukünftige Editoren nicht kümmern.

**Comment by TobiasKrais** [comment]
Ja, gute Idee. Danke.

**Comment by madiko** [comment]
Vielen Dank für die superschnelle Reaktion! Wow, ich bin ehrlich begeistert!
Viel Erfolg bei der Umsetzung. Wäre wirklich klasse, wenn Du das gewuppt bekommst und noch den Vorschlag von Thomas mit einbeziehen kannst dabei.

**Comment by TobiasKrais** [comment]
Die Umsetzung wird ein wenig dauern, da ich erst noch ein wichtiges Projekt fertig machen muss ...

**Comment by skerbis** [comment]
Was so viel heißt wie: PR Welcome ;-) - (Bei mir sieht's zeitlich aber auch nicht so toll aus) . 
Setz mal ein Label "Help wanted" sonst vergesse ich es wieder. @TobiasKrais

**Comment by TobiasKrais** [comment]
Hi Franziska,

jetzt habe ich das mit dem Editor jetzt doch schon implementiert. Die Idee finde ich einfach gut. Hast du Lust zu testen? Falls ja, lade dir den D2U Helper und D2U News aus Git herunter:

- https://github.com/TobiasKrais/d2u_helper/
- https://github.com/TobiasKrais/d2u_news/

Im D2U Helper Addon musst du in die Einstellungen gehen und dort deinen Lieblingseditor festlegen. 

Im D2U News Addon musst du nur noch dein Modul aktualisieren. Dann sollte es funktionieren.

**Comment by madiko** [comment]
Hallo Tobias,
heute und Morgen schaffe ich es leider nicht. Ich schaue es mir gern am Wochenende an.
Bis dahin - gute Zeit und viele Grüße,
Franziska

**Comment by TobiasKrais** [comment]
So, fertig. Das zieht einen Rattenschwanz in allen meinen Adons nach sich. Unterstützt werden jetzt TinyMCE, CKEditor, Redactor und MarkItUp.

@madiko: du kannst dir die aktuelle Version der Addons aus Git ziehen. Dann sollte es funktionieren. Ich habe es inzwischen auch getestet. Bei mir klappt alles. Kann ich den Issue schließen?

**Comment by TobiasKrais** [comment]
Version 1.0.2 ist jetzt veröffentlicht und erfüllt deine Wünsche. Außerdem ist die Abhängigkeit zu tinymce, url und yrewrte Addon entfernt.

**Comment by madiko** [comment]
Hallo Tobias,

endlich kam ich dazu, das AddOn zu testen. Pardon, dass ich Dich da habe so lange warten lassen.

Zum ersten Punkt mit den Abhängigkeiten: Den Vorschlag, den installer an dieser Stelle aufzuwerten, finde ich super. Bleibt zu hoffen, dass das sich nicht zu lange hinzieht ;-)

Zu den Editoren: Wo ziehst Du das genau? Bei mir kommt irgendeine default-Version des Markitup Editors - nicht jedoch mein "default" (darin hatte ich einige Funktionen ausgeblendet, da die gesamte Liste doch recht verwirrend und auch nicht sinnvoll ist).

Ansonsten: Super, dass wir nun die Wahl haben. Finde ich klasse!

Viele Grüße,
Franziska

**Comment by TobiasKrais** [comment]
Hm. Die Profile habe ich hart kodiert. Irgendwie blöd. Die müsste ich aus der Konfig Liste auslesen. Ich denke der Zeitaufwand wäre 30 Minuten das zu ändern.
