### ISSUE TITLE
Unterscheidung in News und Messen - wo?

### ISSUE THREAD

**Issue by madiko** [TobiasKrais/d2u_news#2]
Hallo Tobias,

hatte nun endlich die Gelegenheit, das AddOn bei mir einzubauen und zu testen.

Wie unterscheidest Du in News und Messen? Ich finde dazu keinen "Knopf" oder Auswahl?
Ich schließe nicht aus, das übersehen zu haben - daher gern auch einen Link senden.

Besten Dank und viele Grüße,
Franziska

**Comment by TobiasKrais** [comment]
Hast du das "fairs" plugin installiert?

**Comment by madiko** [comment]
Jetzt ja. Pardon, das hatte ich übersehen.
