### ISSUE TITLE
Anlegen und Zuordnen von Kategorien und Typ?

### ISSUE THREAD

**Issue by madiko** [TobiasKrais/d2u_news#3]
Hallo Tobias,

noch ein Vorschlag für Dein AddOn. Ich würde gern die News nach Kategorien und Typ unterscheiden. 

Kategorien > definiere ich nach Themen
Typ > definiere ich nach Art der News (also z. B. Presse-Info oder Fachbericht / Interview usw.)

Es wäre gut, dann z. B. folgendes auslesen zu können:
Alle [Typ] der [Kategorie], neueste oben
die neuesten [Anzahl] [Typ] der [Kategorie]

Wie aufwändig wäre es, das AddOn dahin weiterzuentwickeln?
Machbar?

Besten Dank und viele Grüße,
Franziska

**Comment by TobiasKrais** [comment]
Ja, machbar. Aufwand ca. 2h. Vorher wäre zu definieren:
- Soll eine Nachricht einer oder mehrerer Kategorien zugeordnet werden können?
- Soll eine Nachricht einem Typ oder mehreren zugeordnet werden können?

Hättest du Lust das in Auftrag zu geben?

**Comment by madiko** [comment]
Mein Vorschlag:

Eingabe der News
Typ sollte eindeutig zugeordnet werden (nur 1 auswählbar)
Kategorien sollten mehrfach zuordenbar sein

Ausgabe der News
Es sollten mehrere Typen (auch alle) auswählbar sein
Es sollten mehrere Kategorien auswählbar sein

**Comment by madiko** [comment]
Als Typen habe ich mal für mich definiert (gern als dummy nutzen)
- News
- Blog
- Interview / Gespräch
- Fachbeitrag
- Reportage / Praxisbericht / Dokumentation
- Presse-Information
- Medien-Echo

**Comment by TobiasKrais** [comment]
OK. Wenn dann machen wir es so, dass du die Typen frei verwalten kannst. Wärst du bereit das in Auftrag zu geben? Dann melde dich einfach über mein Kontaktformular: https://www.design-to-use.de/kontaktfomular/. Das wäre super!

**Comment by madiko** [comment]
Hallo Tobias, 

oh, ich versuchte, Dich heute anzurufen, um ein paar Fragen zu klären. Ich bin nicht so der Online-Kontaktformular-Typ, sorry ich suche dann lieber die direkte E-Mail. Dabei weiß ich einfach nicht, wo und wie das gespeichert wird. Und für jede Seite eine eigene E-Mail-Adresse anlegen, ist auch nervig.

Ungeachtet dessen bin ich beim Adaptieren Deines Moduls auf Schwierigkeiten gestoßen. Die versuche ich gerade zu lösen. Wenn ich das habe, kann ich HOP oder TOP für den Auftrag sagen. Grundsätzlich bin ich offen. Ich würde das gern nur vorab noch für mich klären. Danke.

Ich melde mich und bitte Dich um etwas Geduld bis dahin,
Franziska

**Comment by TobiasKrais** [comment]
Kategorien sind im letzten Commit hinzugefügt worden.

**Comment by TobiasKrais** [comment]
Ab Version 1.1.0 vorhanden. Die Nachrichtenarten sind in ein Plugin ausgelagert. Die neue Version ist im Redaxo Installer vorhanden.

**Comment by madiko** [comment]
Hallo Tobias,

habe alles umgesetzt bekommen. In einem ersten Projekt ist es auch schon live:
http://industrie-initiative.de/informieren-inspirieren

Ein paar Verbesserungsvorschläge habe ich. Interessiert?

Besten Dank und viele Grüße,
Franziska

**Comment by madiko** [comment]
Vielen Dank - ist für mich nun abgeschlossen :-)
