### ISSUE TITLE
syntax error, unexpected 'int' (T_STRING), expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by yanntempel** [TobiasKrais/d2u_news#6]
after installing d2u news addon i get an error when adding my first news article (clicking on +)

[Open: /var/www/vhosts/u52328565.web4.freenetdomain.de/httpdocs/redaxo/src/addons/d2u_news/lib/news.php](atom://core/open/file?filename=/var/www/vhosts/u52328565.web4.freenetdomain.de/httpdocs/redaxo/src/addons/d2u_news/lib/news.php&line=17)
<?php
/**
 * Redaxo D2U News Addon
 * @author Tobias Krais
 * @author <a href="http://www.design-to-use.de">www.design-to-use.de</a>
 */
 
namespace D2U_News;
 
/**
 * News
 */
class News implements \D2U_Helper\ITranslationHelper {
    /**
     * @var int Database ID
     */
    var int $news_id = 0;
    
    /**
     * @var int Redaxo clang id
     */
    var int $clang_id = 0;
    
    /**
     * @var String Name
     */
    var string $name = "";
    
    /**
     * @var String Short description
     */
    var string $teaser = "";
    
    /**
     * @var String Online status. Either "online", "offline" or "archived".
     */
    var string $online_status = "";
 
    /**
     * @var String Picture file name
Arguments
"syntax error, unexpected 'int' (T_STRING), expecting variable (T_VARIABLE)"

in the line:  var int $news_id = 0;

**Comment by yanntempel** [comment]
sorry, here comes the code block

`[Open: /var/www/vhosts/u52328565.web4.freenetdomain.de/httpdocs/redaxo/src/addons/d2u_news/lib/news.php](atom://core/open/file?filename=/var/www/vhosts/u52328565.web4.freenetdomain.de/httpdocs/redaxo/src/addons/d2u_news/lib/news.php&line=17)
<?php
/**
 * Redaxo D2U News Addon
 * @author Tobias Krais
 * @author <a href="http://www.design-to-use.de">www.design-to-use.de</a>
 */
 
namespace D2U_News;
 
/**
 * News
 */
class News implements \D2U_Helper\ITranslationHelper {
    /**
     * @var int Database ID
     */
    var int $news_id = 0;
    
    /**
     * @var int Redaxo clang id
     */
    var int $clang_id = 0;
    
    /**
     * @var String Name
     */
    var string $name = "";
    
    /**
     * @var String Short description
     */
    var string $teaser = "";
    
    /**
     * @var String Online status. Either "online", "offline" or "archived".
     */
    var string $online_status = "";
 
    /**
     * @var String Picture file name
Arguments
"syntax error, unexpected 'int' (T_STRING), expecting variable (T_VARIABLE)"`

` var int $news_id = 0;`

**Comment by TobiasKrais** [comment]
Whats your PHP version?

**Comment by TobiasKrais** [comment]
It should be at least 7.4 or above.

**Comment by yanntempel** [comment]
My php Version is 7.3.x
OK i'll order a newer Version at my Provider and test again.
Thank you
