### ISSUE TITLE
Fehler beim Update von V1.14 auf V1.15

### ISSUE THREAD

**Issue by olien** [TobiasKrais/d2u_news#7]
![image](https://github.com/TobiasKrais/d2u_news/assets/330516/9121f2c0-f0c2-4e78-b03d-48831645a1fc)

**Error:** Class "D2U_Helper\ALangHelper" not found
**File:** redaxo/src/addons/.new.d2u_news/lib/d2u_news_lang_helper.php
**Line:** 5

<details>
<summary>Stacktrace</summary>

| Function                                | File                                                       | Line     |
| --------------------------------------- | ---------------------------------------------------------- | -------- |
| require_once                            | redaxo/src/addons/.new.d2u_news/install.php                | 43       |
| require                                 | redaxo/src/core/lib/packages/package.php                   | 237      |
| rex_package->includeFile                | redaxo/src/addons/.new.d2u_news/update.php                 | 4        |
| require                                 | redaxo/src/core/lib/packages/package.php                   | 233      |
| rex_package->includeFile                | redaxo/src/addons/install/lib/package/package_update.php   | 64       |
| rex_install_package_update->doAction    | redaxo/src/addons/install/lib/package/package_download.php | 47       |
| rex_install_package_download->run       | redaxo/src/addons/install/lib/api/api_package_update.php   | 24       |
| rex_api_install_package_update->execute | redaxo/src/core/lib/api_function.php                       | 197      |
| rex_api_function::handleCall            | redaxo/src/core/backend.php                                | 249      |
| require                                 | redaxo/src/core/boot.php                                   | 157      |
| require                                 | redaxo/index.php                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.17.1, PHP 8.2.0, MySQL 5.7.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.17.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.2.0      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MySQL 5.7.39                   |
| Character set | utf8                           |
|       Warning | Die verwendete MySQL-Version 5.7.39 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Server        |               |
| ------------: | :------------ |
|            OS | Darwin        |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.54 |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/17.0 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |

| Packages                   |            |
| -------------------------: | :--------- |
|               accessdenied | 2.1.0      |
|                    adminer | 2.0.1      |
|                     backup | 2.9.1      |
|                   be_style | 3.4.1      |
|        be_style/customizer | 3.3.1      |
|            be_style/redaxo | 3.4.1      |
|                    bloecks | 4.0.2      |
|           bloecks/cutncopy | 4.0.2      |
|             bloecks/status | 3.1.1      |
|            consent_manager | 4.3.0      |
|                    cronjob | 2.11.0     |
|                 d2u_helper | 1.14.0     |
|                   d2u_news | 1.1.4      |
|                  d2u_staff | 1.2.1      |
|                  developer | 3.9.2      |
|              fa_iconpicker | 1.2.0      |
|                    install | 2.12.1     |
|               lightgallery | 0.4.3      |
|                   markitup | 3.8.0      |
|              media_manager | 2.16.0     |
|                  mediapool | 2.14.0     |
|           mediapool_rename | 1.0.0      |
|                   metainfo | 2.11.0     |
|                      mform | 7.4.4      |
|         navigation_factory | 2.0.3      |
|                     pdfout | 8.1.1      |
|                  phpmailer | 2.13.1     |
|                    project | dev        |
|            project_manager | 1.5.2      |
|     project_manager/client | 1.1.0      |
|           quick_navigation | 7.0.1      |
|                  redactor2 | 4.2.1      |
|                  search_it | 6.10.1     |
|     search_it/autocomplete | 6.10.1     |
|    search_it/documentation | 6.10.1     |
|            search_it/stats | 6.10.1     |
|                 seocheckup | 1.6.8      |
|                      sprog | 1.5.1      |
|                 statistics | 3.1.0      |
|                  structure | 2.17.1     |
|          structure/content | 2.17.1     |
|          structure/history | 2.17.0     |
|                      theme | 1.4.0      |
|                   tinymce4 | 1.2.1      |
|                   ui_tools | 1.2.2      |
| ui_tools/jquery-minicolors | 2.4.0      |
|                      users | 2.11.0     |
|                       ycom | 4.3.0      |
|                  ycom/auth | 4.3.0      |
|                 ycom/group | 4.3.0      |
|                      yform | 4.2.1      |
|                yform/email | 4.2.1      |
|              yform/manager | 4.2.1      |
|                   yrewrite | 2.10.0     |

</details>

**Comment by TobiasKrais** [comment]
Fehler ist leider bekannt. Gemäß Updatehinweis bitte vor dem Update das Addon deaktivieren und danach wieder aktivieren.

**Comment by olien** [comment]
ups. sorry
